In [2]:
#Numpy ===> Numpy is an opensource library that is used for scientific calculation 

# why Numpy is better than list?
# 1. Numpy has more advance functions as compare to list .
# 2.Numpy is homogenous data type while list is heterogenous data type.
# 3.Numpy takes less memory as compare to list .
# 4.Numpy has less execution time as compare to list.

In [3]:
!pip install numpy

In [4]:
import numpy as np

In [5]:
a=[1,34,89]
type (a)

list

In [6]:
b=np.array(a)
b

array([ 1, 34, 89])

In [7]:
a=[[1,2,3],[4,5,6],[7,8,9]]
b=np.array(a)
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
print("total rowS  and column :",b.shape)
print("total element:",b.size)
print("dimension of an array :",b.ndim)

total rowS  and column : (3, 3)
total element: 9
dimension of an array : 2


# How can we create a user defined array?

In [11]:
a =[]
size=int(input("enter the size"))
for i in range(size):
    val= int(input("enter item"))
    a.append(val)
b=np.array(a)
b

enter the size 3
enter item 45
enter item 12
enter item 6


array([45, 12,  6])

# Pre defined functions in numpy


In [12]:
# 1.matrix ----->rows , column 
# 2.in matrix -----> n(rows)=n(columns)----> symmatric matrix ,n(r)!=n(c)---->AS
# 3.diagonal elements ----> [(1,1),(2,2),(3,3),........(n,n)]
# 4.images-------> (0-255)px ---->  Normalize ----bua->(0,1)
# 5.optimization-----> starting weights(m),bias(b)randomly select ----> numpy fuctions

In [18]:
# 1.Zeroes ()------> it will create an array in which all the elements are 0


In [16]:
a=np.zeros(3)
a

array([0., 0., 0.])

In [17]:
b=np.zeros((2,3))
b

array([[0., 0., 0.],
       [0., 0., 0.]])

In [19]:
# 2. ones ()----> it will create an array in which all the element are 1.

In [20]:
a=np.ones(4)
a

array([1., 1., 1., 1.])

In [23]:
a=np.ones((2,3))
a

array([[1., 1., 1.],
       [1., 1., 1.]])

In [25]:
# 3.eye()----> it will create an array in which diagonal position element are 1 and rest all are 0

In [30]:
np.eye(3,4)#asymmatric matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [29]:
np.eye(3) #symmatric matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [28]:
# 4.diag()----> using diag() , we can pass our custom array an diagonal position

In [31]:
a=np.diag([1,45,78,90])
a

array([[ 1,  0,  0,  0],
       [ 0, 45,  0,  0],
       [ 0,  0, 78,  0],
       [ 0,  0,  0, 90]])

In [32]:
# 5.random module 
# (a) randint(min_range,max_range,total_numbers)

In [33]:
np.random.randint(1,10,4)

array([7, 6, 7, 9])

In [ ]:
# (b) rand(total_numbers)----> it will return an array form 0-1

In [34]:
a=np.random.rand(5)
a

array([0.2980827 , 0.43728541, 0.58727092, 0.47949658, 0.05241284])

In [35]:
#seed ()    --->  it will fix the data when it is generated

In [39]:
np.random.seed(30)
a=np.random.randint(1,10,4)
a

array([6, 6, 5, 8])

# View Vs Copy


In [42]:
a=np.array([10,20,30,40,50,70,80])
b=a[2:5]
b[:]=0
b
a

array([10, 20,  0,  0,  0, 70, 80])

In [43]:
a=np.array([10,20,30,40,50,70,80])
b=a[2:5].copy()
b[:]=0
b
a

array([10, 20, 30, 40, 50, 70, 80])

# reshaping the array

In [45]:
# n(rows)*n(column)=n(total elements)

In [46]:
a=np.random.randint(1,100,12)
a

array([ 3, 54, 18, 47,  4, 42,  8, 66, 50, 46, 62, 36])

In [47]:
a.reshape(2,6)

array([[ 3, 54, 18, 47,  4, 42],
       [ 8, 66, 50, 46, 62, 36]])

In [48]:
a.reshape(3,4)

array([[ 3, 54, 18, 47],
       [ 4, 42,  8, 66],
       [50, 46, 62, 36]])

In [54]:
a.reshape(2,2)

ValueError: cannot reshape array of size 12 into shape (2,2)

In [55]:
# 1-60 total_element 36

# conditional selection in nump

In [57]:
a=np.arange(1,15)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [58]:
b=a>10
a[b]

array([11, 12, 13, 14])

In [59]:
a>10

array([False, False, False, False, False, False, False, False, False,
       False,  True,  True,  True,  True])

In [63]:
a=np.arange(1,5).reshape(2,2)
a

array([[1, 2],
       [3, 4]])

In [67]:
a=np.arange(5,9).reshape(2,2)
a

array([[5, 6],
       [7, 8]])

In [69]:
a+b ### 1+5=6 ,2+6=8,3+7=1-,4+8=12

ValueError: operands could not be broadcast together with shapes (2,2) (14,) 

In [70]:
a-b

ValueError: operands could not be broadcast together with shapes (2,2) (14,) 

In [73]:
a.dot(b)


ValueError: shapes (2,2) and (14,) not aligned: 2 (dim 1) != 14 (dim 0)

In [72]:
a/b

ValueError: operands could not be broadcast together with shapes (2,2) (14,) 

In [75]:
# 6. linespace () ---->it will create an array in which gap two values will be equal

In [ ]:
a=np.linespace(1,2,5