# column Transformer

In [1]:
import numpy as np
import pandas as pd

from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import OrdinalEncoder

In [2]:
df=pd.read_csv("C:\\Users\\anski\\Desktop\\kartikey_kichara\\covid_toy.csv")

In [3]:
df

age  gender  fever   cough       city has_covid
0    60    Male  103.0    Mild    Kolkata        No
1    27    Male  100.0    Mild      Delhi       Yes
2    42    Male  101.0    Mild      Delhi        No
3    31  Female   98.0    Mild    Kolkata        No
4    65  Female  101.0    Mild     Mumbai        No
..  ...     ...    ...     ...        ...       ...
95   12  Female  104.0    Mild  Bangalore        No
96   51  Female  101.0  Strong    Kolkata       Yes
97   20  Female  101.0    Mild  Bangalore        No
98    5  Female   98.0  Strong     Mumbai        No
99   10  Female   98.0  Strong    Kolkata       Yes

[100 rows x 6 columns]

In [4]:
df.isnull().sum()

age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

In [5]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test=train_test_split(df.drop(columns=['has_covid']), df['has_covid'], test_size=0.2)

In [6]:
x_train

age  gender  fever   cough       city
7    20  Female    NaN  Strong     Mumbai
87   47    Male  101.0  Strong  Bangalore
36   38  Female  101.0    Mild  Bangalore
58   23    Male   98.0  Strong     Mumbai
66   51    Male  104.0    Mild    Kolkata
..  ...     ...    ...     ...        ...
64   42    Male  104.0    Mild     Mumbai
54   60  Female   99.0    Mild     Mumbai
73   34    Male   98.0  Strong    Kolkata
22   71  Female   98.0  Strong    Kolkata
53   83    Male   98.0    Mild      Delhi

[80 rows x 5 columns]

# Manuallt type Output

In [7]:
#adding simple imputer to fever column
si=SimpleImputer(strategy="mean")
x_train_fever=si.fit_transform(x_train[['fever']])

#also the test data
x_test_fever=si.fit_transform(x_test[['fever']])

x_train_fever.shape

(80, 1)

In [9]:
#ordinal Encoding --> cough
oe=OrdinalEncoder(categories=[['Mild','Strong']])
x_train_cough=oe.fit_transform(x_train[['cough']])

#also the test data
x_test_cough=oe.fit_transform(x_test[['cough']])

x_train_cough.shape

(80, 1)

In [11]:
#oneHotEncoding ---> gender ,City

ohe=OneHotEncoder(drop='first',sparse_output=False)
x_train_gender_city=ohe.fit_transform(x_train[['gender','city']])

#also the test data
x_test_gender_city=ohe.fit_transform([['gender','city']])

x_train_gender_city.shape

(80, 4)

In [1]:
#extracting age
x_train_age=x_train.drop(columns=['gender','fever','cough','city']).values

#also the test data

x_test_age=x_test.drop(columns=['gender','fever','cough','city']).values


NameError: name 'x_train' is not defined

# by the help of column Transformer


In [17]:
from sklearn.compose import ColumnTransformer #this is how to import Column

transformer=ColumnTransformer(transformers=[('tnf1',SimpleImputer(),['fever']),
                                            ('tnf2',OrdinalEncoder(categories=[['Mild','Strong']]),['cough']),
                                            ('tnf3',OneHotEncoder(sparse_output=False,drop='first'),['gender','city'])
                                           ],remainder='passthrough')

In [18]:
transformer.fit_transform(x_train).shape

(80, 7)

 <!-- # Function Transformer -->
The Function Transformer is a tool in scikit-learn , a popular Python library for machine Learning , that allows you to apply a specified function to the input data. The function Transformer can be useful for performingn custom transformations of input data in a machine learning pipeline


In [22]:
from sklearn.preprocessing import FunctionTransformer
import numpy as np

#creates a dataset
X=np.array([[1,2],[3,4]])

#define the transformation function
log_transform=FunctionTransformer(np.log1p)

#apply the transformation to the dataset
X_transformed=log_transform.transform(X)

print(X_transformed)

[[0.69314718 1.09861229]
 [1.38629436 1.60943791]]


In [25]:
#1.custom Feature Engineering
from sklearn.preprocessing import FunctionTransformer
import numpy as np

#creates adataset
X=np.array([[1,2],[3,4]])

#define a custom feature engineering function

def sakrat_14(X):
    return np.hstack((X,X**2))

custom_transformer=FunctionTransformer(sakrat_14)

X_transformed=custom_transformer.transform(X)

print(X_transformed)

[[ 1  2  1  4]
 [ 3  4  9 16]]


In [27]:
#2 Scaling and Normalization
from sklearn.preprocessing import FunctionTransformer
import numpy as np

#create a dataset
X=np.array([[1,2],[3,4]])

def myscaling(X):
    return X/np.max(X)

custom_transformer=FunctionTransformer(myscaling)

X_transformed=custom_transformer.transform(X)

print(X_transformed)

[[0.25 0.5 ]
 [0.75 1.  ]]


In [28]:
# 3 Data Cleaning
from sklearn.preprocessing import FunctionTransformer
import numpy as np

X=np.array([[1,2],[3,np.nan]])

def my_cleaning(X):
    X[np.isnan(X)]=0
    return X

custom_transformer=FunctionTransformer(my_cleaning)

X_transformed=custom_transformer.transform(X)

print(X_transformed)

[[1. 2.]
 [3. 0.]]


In [29]:
import numpy as np 
import pandas as pd


In [31]:
df=pd.read_csv("C:\\Users\\anski\\Desktop\\kartikey_kichara\\placement.csv")

In [32]:
df

cgpa  resume_score  placed
0   8.14          6.52       1
1   6.17          5.17       0
2   8.27          8.86       1
3   6.88          7.27       1
4   7.52          7.30       1
..   ...           ...     ...
95  6.33          6.38       0
96  8.23          7.76       1
97  6.65          7.78       0
98  8.14          5.63       1
99  6.09          6.61       0

[100 rows x 3 columns]

In [33]:
x=df.drop(columns=['placed'])
y=df['placed']
from sklearn.preprocessing import FunctionTransformer


In [35]:
#define the transformation function
log_transform=FunctionTransformer(np.log1p)

#apply the transformation to the dataset
X_transformed=log_transform.transform(x)

X_transformed

cgpa  resume_score
0   2.212660      2.017566
1   1.969906      1.819699
2   2.226783      2.288486
3   2.064328      2.112635
4   2.142416      2.116256
..       ...           ...
95  1.991976      1.998774
96  2.222459      2.170196
97  2.034706      2.172476
98  2.212660      1.891605
99  1.958685      2.029463

[100 rows x 2 columns]