# Pandas


In [1]:
# Pandas ----> Pandas is an open source library that is used for handle data manipulation.

In [2]:
# Installation of Pandas
!pip install pandas

In [4]:
import pandas as pd

In [5]:
# data structure of pandas
# 1.series 
# # 2.data frame

In [6]:
# 1.series ----> it is one dimensional array and it returns only values not column name.

In [7]:
a=pd.Series([1,34,55,77,88])
a

0     1
1    34
2    55
3    77
4    88
dtype: int64

In [7]:
type(a)

pandas.core.series.Series

In [8]:
# 2. Dataframe -----> it is multi- dimensional array and it returns values with column name.

In [9]:
a={
    "Emp_Id" : [1,2,3,4,5],
    "Name" :['sam','ajay','ashish','kk','sohan'],
    "Working_hours" :[8,8,8,5,6],
    "Salary" : [25000,23000,60000,20000,45000]
}

In [10]:
type(a)

dict

In [11]:
df=pd.DataFrame(a)
df

Emp_Id    Name  Working_hours  Salary
0       1     sam              8   25000
1       2    ajay              8   23000
2       3  ashish              8   60000
3       4      kk              5   20000
4       5   sohan              6   45000

# how to import and export the dataframe

In [12]:
# 1.Export
df.to_csv("C:\\Users\\anski\\Desktop\\kartikey_kichara\\Emp_info.csv",index=False)

In [13]:
# 2.Import 
df2=pd.read_csv("C:\\Users\\anski\\Desktop\\kartikey_kichara\\Emp_info.csv")
df2

Emp_Id    Name  Working_hours  Salary
0       1     sam              8   25000
1       2    ajay              8   23000
2       3  ashish              8   60000
3       4      kk              5   20000
4       5   sohan              6   45000

In [20]:
df.to_excel("C:\\Users\\anski\\Desktop\\kartikey_kichara\\updated_file.xlsx")

In [21]:
# #Assignment ------>
# dataframe 

In [34]:
a={
    "Student_Id" :[1,2,3,4,5,6,7,8,9,10],
    "Student_Name" :["Ajay","Rohan","Sohan","Raju","Kartikey","Arpit","Ashish","Mohit","Anshul","Abhay"],
    "Roll_No" :[20,21,22,23,24,25,26,27,28,29,30],
    "Section" :["A","A","B","B","C","D","E","D","E","C"],
    "Batch":["A1","A1","A2","A2","A3","A1","A2","A4","A4","A3"],
    "Domain" :["AWS","PYTHON DJANGO","AWS","DATA SCIENCE","DATA ENGINEERING ","JAVA FULL STACKN","DATA SCIENCE","DATA ENGINEERING","DATA ANALYST","C++"]
}

In [35]:
df= pd.DataFrame(a)
df

ValueError: All arrays must be of the same length

# Q1. Write statement to import numpy?

In [37]:
import numpy as np

In [38]:
#create an array using numpy?
a=[1,2,5,6,8]
a

[1, 2, 5, 6, 8]

In [39]:
b=np.array(a)
b

array([1, 2, 5, 6, 8])

In [40]:
#create an array of 10 random integer?
np.random.randint(1,50,10)

array([35,  4,  5, 38, 29, 23, 31, 37, 41, 23])

In [42]:
#create an array of elements 10-20?
arr=np.arange(10,21)
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])