In [1]:
import numpy as np 
import pandas as pd

In [2]:
df=pd.read_csv("C:\\Users\\anski\\Desktop\\all_folder\\Datasets\\covid_toy.csv")

In [3]:
df.head()

age  gender  fever cough     city has_covid
0   60    Male  103.0  Mild  Kolkata        No
1   27    Male  100.0  Mild    Delhi       Yes
2   42    Male  101.0  Mild    Delhi        No
3   31  Female   98.0  Mild  Kolkata        No
4   65  Female  101.0  Mild   Mumbai        No

In [4]:
df.shape


(100, 6)

In [5]:
df=df.dropna()

In [6]:
df.isnull().sum()

age          0
gender       0
fever        0
cough        0
city         0
has_covid    0
dtype: int64

In [7]:
df.dtypes

age            int64
gender        object
fever        float64
cough         object
city          object
has_covid     object
dtype: object

In [8]:
from sklearn.preprocessing import OrdinalEncoder

In [9]:
df=df.drop(columns=['fever','age'])

In [10]:
df.head(12)

gender   cough       city has_covid
0     Male    Mild    Kolkata        No
1     Male    Mild      Delhi       Yes
2     Male    Mild      Delhi        No
3   Female    Mild    Kolkata        No
4   Female    Mild     Mumbai        No
6     Male  Strong  Bangalore        No
8   Female  Strong  Bangalore        No
9   Female    Mild      Delhi        No
11  Female    Mild     Mumbai       Yes
12  Female  Strong    Kolkata        No
13    Male    Mild  Bangalore       Yes
14    Male    Mild  Bangalore        No

In [11]:
df.nunique()

gender       2
cough        2
city         4
has_covid    2
dtype: int64

In [12]:
oe=OrdinalEncoder(categories=[['Male','Female'],
                              ['Mild','Strong'],
                              ['Kolkata','Delhi','Mumbai','Bangalore'],
                              ['Yes','No']
                             ])

In [13]:
oe.fit_transform(df)

array([[0., 0., 0., 1.],
       [0., 0., 1., 0.],
       [0., 0., 1., 1.],
       [1., 0., 0., 1.],
       [1., 0., 2., 1.],
       [0., 1., 3., 1.],
       [1., 1., 3., 1.],
       [1., 0., 1., 1.],
       [1., 0., 2., 0.],
       [1., 1., 0., 1.],
       [0., 0., 3., 0.],
       [0., 0., 3., 1.],
       [0., 1., 0., 0.],
       [1., 0., 0., 0.],
       [1., 1., 1., 1.],
       [1., 0., 3., 0.],
       [0., 1., 3., 1.],
       [0., 0., 3., 0.],
       [1., 1., 0., 0.],
       [1., 0., 1., 0.],
       [1., 1., 0., 1.],
       [1., 0., 0., 0.],
       [1., 1., 1., 1.],
       [0., 0., 0., 1.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [1., 1., 1., 0.],
       [1., 0., 0., 1.],
       [0., 0., 2., 0.],
       [1., 1., 3., 1.],
       [1., 0., 3., 1.],
       [0., 0., 0., 1.],
       [1., 0., 1., 0.],
       [1., 0., 0., 1.],
       [1., 0., 1., 1.],
       [0., 0., 1., 0.],
       [1., 0., 3., 0.],
       [0., 1., 1., 1.],
       [0., 0., 3., 1.],
       [1., 0., 2., 1.],


In [14]:
df

gender   cough       city has_covid
0     Male    Mild    Kolkata        No
1     Male    Mild      Delhi       Yes
2     Male    Mild      Delhi        No
3   Female    Mild    Kolkata        No
4   Female    Mild     Mumbai        No
..     ...     ...        ...       ...
95  Female    Mild  Bangalore        No
96  Female  Strong    Kolkata       Yes
97  Female    Mild  Bangalore        No
98  Female  Strong     Mumbai        No
99  Female  Strong    Kolkata       Yes

[90 rows x 4 columns]

In [15]:
from sklearn.preprocessing import OneHotEncoder

In [16]:
df=df.dropna()

In [17]:
ohe=OneHotEncoder(drop='first',sparse_output=False,dtype=np.int32)

In [18]:
df_new=ohe.fit_transform(df[['gender','cough','city','has_covid']])

In [19]:
df_new

array([[1, 0, 0, 1, 0, 0],
       [1, 0, 1, 0, 0, 1],
       [1, 0, 1, 0, 0, 0],
       [0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 1, 0],
       [1, 1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 1, 1],
       [0, 1, 0, 1, 0, 0],
       [1, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0],
       [1, 1, 0, 1, 0, 1],
       [0, 0, 0, 1, 0, 1],
       [0, 1, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 1],
       [1, 1, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 1],
       [0, 1, 0, 1, 0, 1],
       [0, 0, 1, 0, 0, 1],
       [0, 1, 0, 1, 0, 0],
       [0, 0, 0, 1, 0, 1],
       [0, 1, 1, 0, 0, 0],
       [1, 0, 0, 1, 0, 0],
       [1, 0, 1, 0, 0, 1],
       [1, 0, 0, 1, 0, 0],
       [0, 1, 1, 0, 0, 1],
       [0, 0, 0, 1, 0, 0],
       [1, 0, 0, 0, 1, 1],
       [0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [1, 0, 0, 1, 0, 0],
       [0, 0, 1, 0, 0, 1],
       [0, 0, 0, 1, 0, 0],
       [0, 0, 1, 0, 0, 0],
       [1, 0, 1, 0, 0, 1],
       [0, 0, 0, 0, 0, 1],
 

In [22]:
a=pd.get_dummies(df,columns=['gender','cough','city','has_covid'],drop_first=True)

In [24]:
a=a.astype(int)

In [25]:
a

gender_Male  cough_Strong  city_Delhi  city_Kolkata  city_Mumbai  \
0             1             0           0             1            0   
1             1             0           1             0            0   
2             1             0           1             0            0   
3             0             0           0             1            0   
4             0             0           0             0            1   
..          ...           ...         ...           ...          ...   
95            0             0           0             0            0   
96            0             1           0             1            0   
97            0             0           0             0            0   
98            0             1           0             0            1   
99            0             1           0             1            0   

    has_covid_Yes  
0               0  
1               1  
2               0  
3               0  
4               0  
..            ...  
95              0  
96              1  
97              0  
98              0  
99              1  

[90 rows x 6 columns]

In [26]:
import numpy as np
import pandas as pd

In [27]:
df=pd.read_csv("C:\\Users\\anski\\Desktop\\all_folder\\Datasets\\covid_toy.csv")

In [28]:
df.head()

age  gender  fever cough     city has_covid
0   60    Male  103.0  Mild  Kolkata        No
1   27    Male  100.0  Mild    Delhi       Yes
2   42    Male  101.0  Mild    Delhi        No
3   31  Female   98.0  Mild  Kolkata        No
4   65  Female  101.0  Mild   Mumbai        No

In [29]:
df.isnull().sum()

age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

In [30]:
df=df.dropna()

In [31]:
df.isnull().sum()

age          0
gender       0
fever        0
cough        0
city         0
has_covid    0
dtype: int64

In [32]:
from sklearn.preprocessing import OrdinalEncoder

In [33]:
df=df.drop(columns=['age','fever'])

In [34]:
df

gender   cough       city has_covid
0     Male    Mild    Kolkata        No
1     Male    Mild      Delhi       Yes
2     Male    Mild      Delhi        No
3   Female    Mild    Kolkata        No
4   Female    Mild     Mumbai        No
..     ...     ...        ...       ...
95  Female    Mild  Bangalore        No
96  Female  Strong    Kolkata       Yes
97  Female    Mild  Bangalore        No
98  Female  Strong     Mumbai        No
99  Female  Strong    Kolkata       Yes

[90 rows x 4 columns]

In [35]:
oe=OrdinalEncoder(categories=[['Male','Female'],
                              ['Mild','Strong'],
                              ['Kolkata','Mumbai','Bangalore','Delhi'],
                              ['Yes','No']])


In [36]:
oe.fit_transform(df)

array([[0., 0., 0., 1.],
       [0., 0., 3., 0.],
       [0., 0., 3., 1.],
       [1., 0., 0., 1.],
       [1., 0., 1., 1.],
       [0., 1., 2., 1.],
       [1., 1., 2., 1.],
       [1., 0., 3., 1.],
       [1., 0., 1., 0.],
       [1., 1., 0., 1.],
       [0., 0., 2., 0.],
       [0., 0., 2., 1.],
       [0., 1., 0., 0.],
       [1., 0., 0., 0.],
       [1., 1., 3., 1.],
       [1., 0., 2., 0.],
       [0., 1., 2., 1.],
       [0., 0., 2., 0.],
       [1., 1., 0., 0.],
       [1., 0., 3., 0.],
       [1., 1., 0., 1.],
       [1., 0., 0., 0.],
       [1., 1., 3., 1.],
       [0., 0., 0., 1.],
       [0., 0., 3., 0.],
       [0., 0., 0., 1.],
       [1., 1., 3., 0.],
       [1., 0., 0., 1.],
       [0., 0., 1., 0.],
       [1., 1., 2., 1.],
       [1., 0., 2., 1.],
       [0., 0., 0., 1.],
       [1., 0., 3., 0.],
       [1., 0., 0., 1.],
       [1., 0., 3., 1.],
       [0., 0., 3., 0.],
       [1., 0., 2., 0.],
       [0., 1., 3., 1.],
       [0., 0., 2., 1.],
       [1., 0., 1., 1.],


In [37]:
from sklearn.preprocessing import OneHotEncoder

In [39]:
ohe=OneHotEncoder(drop="first",sparse_output=False,dtype=np.int32)

In [42]:
df_new=ohe.fit_transform(df[['gender','cough','city','has_covid']])

In [43]:
df_new

array([[1, 0, 0, 1, 0, 0],
       [1, 0, 1, 0, 0, 1],
       [1, 0, 1, 0, 0, 0],
       [0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 1, 0],
       [1, 1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 1, 1],
       [0, 1, 0, 1, 0, 0],
       [1, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0],
       [1, 1, 0, 1, 0, 1],
       [0, 0, 0, 1, 0, 1],
       [0, 1, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 1],
       [1, 1, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 1],
       [0, 1, 0, 1, 0, 1],
       [0, 0, 1, 0, 0, 1],
       [0, 1, 0, 1, 0, 0],
       [0, 0, 0, 1, 0, 1],
       [0, 1, 1, 0, 0, 0],
       [1, 0, 0, 1, 0, 0],
       [1, 0, 1, 0, 0, 1],
       [1, 0, 0, 1, 0, 0],
       [0, 1, 1, 0, 0, 1],
       [0, 0, 0, 1, 0, 0],
       [1, 0, 0, 0, 1, 1],
       [0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [1, 0, 0, 1, 0, 0],
       [0, 0, 1, 0, 0, 1],
       [0, 0, 0, 1, 0, 0],
       [0, 0, 1, 0, 0, 0],
       [1, 0, 1, 0, 0, 1],
       [0, 0, 0, 0, 0, 1],
 

In [47]:
a=pd.get_dummies(df,columns=['gender','cough','city','has_covid'],drop_first=True)

In [48]:
a

gender_Male  cough_Strong  city_Delhi  city_Kolkata  city_Mumbai  \
0          True         False       False          True        False   
1          True         False        True         False        False   
2          True         False        True         False        False   
3         False         False       False          True        False   
4         False         False       False         False         True   
..          ...           ...         ...           ...          ...   
95        False         False       False         False        False   
96        False          True       False          True        False   
97        False         False       False         False        False   
98        False          True       False         False         True   
99        False          True       False          True        False   

    has_covid_Yes  
0           False  
1            True  
2           False  
3           False  
4           False  
..            ...  
95          False  
96           True  
97          False  
98          False  
99           True  

[90 rows x 6 columns]